export const PLAYER_START = 'PLAYER_START';
export const PLAYER_STOP = 'PLAYER_STOP';
export const PLAYER_PLAYED = 'PLAYER_PLAYED';

export const PLAYER_SAVE_TRACK = 'PLAYER_SAVE_TRACK';

export const PLAYER_PAUSE = 'PLAYER_PAUSE';
export const PLAYER_RESUME = 'PLAYER_RESUME';

export const PLAYER_NEXT = 'PLAYER_NEXT';
export const PLAYER_PREV = 'PLAYER_PREV';

export const PLAYER_PROGRESS = 'PLAYER_PROGRESS';
export const PLAYER_ENDED = 'PLAYER_ENDED';
export const PLAYER_CLEAR = 'PLAYER_CLEAR';

export const SET_TRACK_INFO = 'SET_TRACK_INFO';
export const SET_PLAYLIST = 'SET_PLAYLIST';
export const PLAYER_GET_RADIO = 'PLAYER_GET_RADIO';

export const TOGGLE_REPEAT = 'TOGGLE_REPEAT';

